### Login user
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "pokopang",
  "password": "123"
}
> {% client.global.set("authToken", response.body.data.token); %}

### Create contact
POST http://localhost:3000/api/contacts
Authorization: {{authToken}}
Content-Type: application/json

{
  "first_name": "Dark",
  "last_name": "Pokopang",
  "email": "dark@pokopang.com",
  "phone": "+61123456"
}

### Get by contact id
GET http://localhost:3000/api/contacts/1
Authorization: {{authToken}}

### Edit contact by id
PUT http://localhost:3000/api/contacts/1
Authorization: {{authToken}}
Content-Type: application/json

{
  "first_name": "Light"
}

### Delete contact by id
DELETE http://localhost:3000/api/contacts/1
Authorization: {{authToken}}

### Search contact
GET http://localhost:3000/api/contacts?name=li
Authorization: {{authToken}}